-- ==========================================
-- CRM Schema Design - Phase 1: Lead Management
-- Database: PostgreSQL
-- ==========================================

-- 1. Create Users Table (Assignees/Owners)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Create Lead Statuses Table (Master Lookup)
CREATE TABLE lead_statuses (
    id VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Create Lead Sources Table (Master Lookup)
CREATE TABLE lead_sources (
    id VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 4. Create Leads Table
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    company_name VARCHAR(100),
    title VARCHAR(100),
    email VARCHAR(100),
    phone VARCHAR(20),
    status_id VARCHAR(50) NOT NULL,
    source_id VARCHAR(50),
    assigned_to BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(50) NOT NULL DEFAULT 'system',
    
    CONSTRAINT fk_leads_status FOREIGN KEY (status_id) REFERENCES lead_statuses(id),
    CONSTRAINT fk_leads_source FOREIGN KEY (source_id) REFERENCES lead_sources(id),
    CONSTRAINT fk_leads_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

-- 5. Create Lead Interactions Table
CREATE TABLE lead_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    interaction_type VARCHAR(50) NOT NULL, -- e.g., 'NOTE', 'CALL', 'EMAIL', 'MEETING'
    details TEXT NOT NULL,
    interaction_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_interactions_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
    CONSTRAINT fk_interactions_user FOREIGN KEY (created_by) REFERENCES users(id)
);

-- ==========================================
-- Recommended Indexes for Performance & Search
-- ==========================================
CREATE INDEX idx_leads_status_id ON leads(status_id);
CREATE INDEX idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX idx_leads_email ON leads(email);
CREATE INDEX idx_leads_last_name ON leads(last_name);
CREATE INDEX idx_interactions_lead_id ON lead_interactions(lead_id, interaction_date DESC);

-- ==========================================
-- Seed Data for Master Configuration Tables
-- ==========================================

-- Seed Lead Statuses
INSERT INTO lead_statuses (id, display_name, description, sort_order, is_active) VALUES
('NEW', 'New', 'Freshly added lead with no outreach yet', 10, true),
('CONTACTED', 'Contacted', 'First outreach made (email/phone)', 20, true),
('QUALIFIED', 'Qualified', 'Verified interest and budget match', 30, true),
('LOST', 'Lost', 'Not interested or bad fit', 40, true)
ON CONFLICT (id) DO NOTHING;

-- Seed Lead Sources
INSERT INTO lead_sources (id, display_name, description, is_active) VALUES
('WEBSITE', 'Website', 'Lead submitted via the contact form', true),
('COLD_CALL', 'Cold Call', 'Outbound sales call', true),
('REFERRAL', 'Referral', 'Word of mouth or partner referral', true),
('EMAIL_CAMPAIGN', 'Email Campaign', 'Inbound response from marketing campaigns', true)
ON CONFLICT (id) DO NOTHING;
